usage() {
  echo "用法: raspa-scale [选项] <并发上限|省略以交互> [子目录]"
  echo "说明: 在当前工作目录下，设置允许并发的最大工人数；可选指定子目录（默认自动检测）"
  echo "      在SLURM loop模式下：会自动补交/取消作业以接近目标值；在PBS下已支持按编号安全自动补交/回收。"
  echo "      默认行为: 终端可交互且未提供并发上限时，自动进入交互模式。"
  echo ""
  echo "快速终止任务:"
  echo "  raspa-scale kill [选项]"
  echo "  说明: 直接调用调度器终止任务（不限于 raspa-scale 提交的高通量任务）"
  echo "  查看详细参数: raspa-scale kill -h"
  echo ""
  echo "任务状态:"
  echo "  raspa-scale status [选项] [子目录]"
  echo "  说明: 查看/重置任务状态（等价 raspa-status）"
  echo "选项:"
  echo "  -i, --interactive, interactive  进入交互模式，先展示集群资源与可用任务，再输入并发上限"
  echo "  -h, --help                      显示此帮助信息"
  echo "  -y, --accept                    非交互自动采用建议值（无标准输入或CI中很有用）"
  echo "  -a, --apply                     写入并发上限并执行自动扩/缩容（必须显式指定）"
  echo "      --limit-only                仅写入并发上限，不提交/取消作业"
}

kill_usage() {
  echo "用法: raspa-scale kill [选项]"
  echo "说明: 需要 SLURM 环境 (scancel/squeue)"
  echo "选项:"
  echo "  -u, --user <用户名>           删除指定用户的所有任务"
  echo "  -n, --node <节点列表>        按节点终止任务（如 nodeA:5,nodeB:3；可配合 -c）"
  echo "  -c, --count <数量>           未在节点列表中指定数量时，默认每个节点终止的任务数"
  echo "  -r, --range <开始-结束>       删除指定范围的作业ID (例如: -r 12894-13421)"
  echo "  -l, --list <作业ID列表>       删除指定的作业ID列表 (例如: -l 12894,12895,13421)"
  echo "  -f, --force                   跳过确认，直接删除"
  echo "  -h, --help                    显示此帮助信息"
  echo ""
  echo "示例:"
  echo "  raspa-scale kill -u zjp"
  echo "  raspa-scale kill -n worker-node-01:10"
  echo "  raspa-scale kill -n worker-node-01,worker-node-02 -c 5"
  echo "  raspa-scale kill -r 12894-13421"
  echo "  raspa-scale kill -l 12894,12895,13421"
}
