#!/bin/bash

set -euo pipefail

usage_short() {
  usage
}

usage() {
  echo "用法: raspa-scale [选项] [并发上限] [子目录]"
  echo ""
  echo "说明:"
  echo "  动态调整高通量计算的并发度（扩容/缩容），并在作业被打断后自动补齐缺失作业。"
  echo "  在 SLURM 环境下自动补交/取消作业以接近目标并发；PBS 环境仅更新并发上限文件。"
  echo "  终端可交互且未提供并发上限时，自动进入交互模式（菜单选择）。"
  echo ""
  echo "子命令:"
  echo "  kill [选项]              终止调度器任务（不限于 raspa-scale 提交的任务）"
  echo "                           详细参数: raspa-scale kill -h"
  echo "  status [选项] [子目录]   查看/重置任务状态（等价 raspa-status）"
  echo ""
  echo "选项:"
  echo "  -i, --interactive        进入交互模式，展示集群资源与可用任务后手动输入并发上限"
  echo "  -y, --accept             非交互模式，自动采用建议并发值并执行扩缩容（适合 CI/无终端）"
  echo "  -a, --apply <并发数>     写入并发上限并立即执行自动扩/缩容"
  echo "      --limit-only <并发数> 仅写入 .raspa_worker_limit，不提交/取消任何作业"
  echo "  -h, --help               显示此帮助信息"
  echo ""
  echo "环境变量:"
  echo "  RASPA_SCALE_RECOMMEND=auto|run_idle|idle|full"
  echo "                           推荐并发策略（默认 auto：运行中+集群空闲，不超过任务总数）"
  echo "  RASPA_SCALE_SCAN_JOBS=N  并行扫描任务目录的线程数（默认自动，最多32）"
  echo "  RASPA_SCALE_SCAN_MODE=auto|fast|verify"
  echo "                           任务统计模式（auto 在任务数超阈值时切换为 fast）"
  echo "  RASPA_SCALE_SCAN_FAST_THRESHOLD=N"
  echo "                           auto 模式触发 fast 的任务数阈值（默认 2000）"
  echo "  RASPA_SCALE_SCAN_CACHE_SEC=N"
  echo "                           任务统计缓存秒数（默认 15，避免重复扫描）"
  echo "  RASPA_SLURM_FREE_POLICY=alloc_ht|alloc|min|load"
  echo "                           可用线程数估算策略（默认 alloc_ht：超线程节点取 min(alloc,load)）"
  echo "  RASPA_SCALE_KILL_FORCE=1 跳过缩容确认（非交互场景强制执行）"
  echo ""
  echo "示例:"
  echo "  raspa-scale                      # 交互模式（菜单选择）"
  echo "  raspa-scale -y                   # 自动采用建议并发并补交"
  echo "  raspa-scale -a 256               # 设置并发256并立即扩缩容"
  echo "  raspa-scale --limit-only 128     # 仅写入上限，不提交作业"
  echo "  raspa-scale kill -u zjp          # 终止用户 zjp 的所有任务"
  echo "  raspa-scale kill -n worker-node-01:10,worker-node-02:5"
  echo "  raspa-scale kill -r 12894-13421  # 按作业ID范围终止"
  echo "  raspa-scale kill -l 12894,12895  # 按作业ID列表终止"
}

kill_usage() {
  echo "用法: raspa-scale kill [选项]"
  echo "说明: 需要 SLURM 环境 (scancel/squeue)"
  echo "选项:"
  echo "  -u, --user <用户名>           删除指定用户的所有任务"
  echo "  -n, --node <节点列表>        按节点终止任务（如 nodeA:5,nodeB:3；可配合 -c）"
  echo "  -c, --count <数量>           未在节点列表中指定数量时，默认每个节点终止的任务数"
  echo "  -r, --range <开始-结束>       删除指定范围的作业ID (例如: -r 12894-13421)"
  echo "  -l, --list <作业ID列表>       删除指定的作业ID列表 (例如: -l 12894,12895,13421)"
  echo "  -f, --force                   跳过确认，直接删除"
  echo "  -h, --help                    显示此帮助信息"
  echo ""
  echo "示例:"
  echo "  raspa-scale kill -u zjp"
  echo "  raspa-scale kill -n worker-node-01:10"
  echo "  raspa-scale kill -n worker-node-01,worker-node-02 -c 5"
  echo "  raspa-scale kill -r 12894-13421"
  echo "  raspa-scale kill -l 12894,12895,13421"
}
