from raspa_calc.runtime import config as config_module


def show_help():
    """Show help text."""
    print(f"RASPA 高通量计算工具 v{config_module.__version__} ({config_module.__version_name__})")
    print()
    print("用法: raspa-calc [选项]")
    print()
    print("选项:")
    print("  -h, --help          显示此帮助信息")
    print("  -v, --version       显示版本信息")
    print("  --no-check          跳过环境检测")
    print()
    print("支持的 RASPA 版本:")
    print("  • RASPA2 - 传统版本 (simulation.input)")
    print("  • RASPA3 - 新版本 (simulation.json)")
    print("  在 config.yaml 中设置 raspa_version: 'raspa2' 或 'raspa3'")
    print()
    print("计算模式:")
    print("  1. 参数筛选模式（小批量运算）")
    print("     - 用于测试和参数优化")
    print("     - 默认使用2个CPU核心")
    print("     - 适合少量结构的快速验证")
    print()
    print("  2. 高通量计算模式（大规模计算）")
    print("     - 用于大规模计算")
    print("     - 支持用户指定CPU核心数")
    print("     - 支持多节点集群(960+CPU核心)")
    print("     - 自动检测任务数量并智能分配")
    print()
    print("  3. 数据提取模式（从计算结果中提取数据）")
    print("     - 从计算结果中提取关键数据")
    print("     - 自动检测 RASPA2/RASPA3 输出格式")
    print("     - 生成Excel表格")
    print()
    print("  4. 警告处理模式（处理计算中的警告任务）")
    print("     - 扫描CSV中的警告信息并创建独立任务")
    print()
    print("  5. 等温线绘制模式（批量绘制MOF等温吸附曲线）")
    print("     - 自动扫描计算结果目录并输出图片")
    print()
    print("  6. CSV/CIF 筛选模式（MOF筛选器）")
    print("     - 交互式按条件/refcode筛选CSV并可复制对应CIF")
    print()
    print("v2.5.0 新特性:")
    print("  ✅ CSV/CIF 筛选模式 - 直接从 raspa-calc 入口调用 MOF 筛选工具")
    print()
    print("v2.4.0 新特性:")
    print("  ✅ RASPA3 支持 - 完整支持 RASPA3 版本")
    print("  ✅ 版本自动检测 - 自动识别输出文件格式")
    print("  ✅ 双版本配置 - 配置文件支持切换版本")
    print()
    print("v2.3.0 特性:")
    print("  ✅ 多节点集群支持 - NFS共享存储实现跨节点调度")
    print("  ✅ 任务提交延迟优化 - 避免调度器过载导致节点异常")
    print("  ✅ 配置参数化 - 框架列名等参数完全可配置")
    print()
    print("示例:")
    print("  raspa-calc               # 交互式选择模式")
    print("  raspa-calc -h            # 显示帮助")
    print("  raspa-calc -v            # 显示版本")
    print()
    print("相关命令:")
    print("  raspa-status             # 查看任务状态")
    print("  raspa-diagnose           # 运行诊断")
    print()
    print("多节点集群使用:")
    print("  ⚠️  重要: 必须在NFS挂载目录下提交任务")
    print("  cd /home/zjp/raspa2-calc  # 进入NFS共享目录")
    print("  raspa-calc               # 启动高通量计算")
    print()


def show_version():
    """Show version."""
    print(f"RASPA 高通量计算工具 v{config_module.__version__} ({config_module.__version_name__})")
    print()
    print("版本特性:")
    print("  ✅ CSV/CIF 筛选模式 - 直接在主菜单运行 MOF 筛选器")
    print("  ✅ RASPA2/RASPA3 双版本支持 - 可在配置文件中切换版本")
    print("  ✅ 版本自动检测 - 自动识别输出文件格式进行数据提取")
    print("  ✅ 多节点集群支持 - 支持SLURM集群跨节点调度(960+CPU核心)")
    print("  ✅ 任务提交优化 - 智能延迟避免调度器过载和Prolog error")
    print("  ✅ 配置参数化 - 支持从配置文件读取所有参数")
    print("  ✅ 精确UnitCells算法 - 基于向量叉积的精确计算")
    print("  ✅ gemmi库集成 - 专业CIF文件处理和晶体学计算")
    print()
